spring:
  application:
    name: notification-service
  datasource:
    url: ${DB_URL_NOTIFICATION:jdbc:postgresql://localhost:5432/notification_db}
    username: ${DB_USERNAME_NOTIFICATION:postgres}
    password: ${DB_PASSWORD_NOTIFICATION:password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${SERVER_PORT:8086}
