spring.application.name=transport-service

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/harvestconnect_transport
spring.datasource.username=postgres
spring.datasource.password=Amen@2008

# JPA & Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


