spring:
  application:
    name: transport-service
  datasource:
    url: jdbc:${DB_URL_TRANSPORT:postgresql://localhost:5432/transport_db}?currentSchema=transport
    username: ${DB_USERNAME_TRANSPORT:postgres}
    password: ${DB_PASSWORD_TRANSPORT:password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${SERVER_PORT:8083}
