### Test 1: Create a Truck Listing
POST http://localhost:8080/api/transport/listings
Content-Type: application/json
X-User-Id: transporter_godwin
X-User-Role: TRANSPORTER

{
  “truckType”: “Flatbed Heavy Duty”,
  “capacityTons”: 15.0,
  “currentLocation”: “Kumasi”,
  “destination”: “Tamale”,
  “price_per_ton”: 250.00,
  “departureDate”: “2026-07-20”
}


### Test 2: Search Listings
GET http://localhost:8080/api/transport/listings?currentLocation=Kumasi&destination=Tamale


### Test 3: Book Truck Space
POST http://localhost:8080/api/transport/bookings
Content-Type: application/json
X-User-Id: farmer_kwame
X-User-Role: FARMER

{
  “truckListingId”: 1,
  “quantityTons”: 5.0
}


### Test 4: Confirm Booking
PUT http://localhost:8080/api/transport/bookings/1/confirm
X-User-Id: transporter_godwin
X-User-Role: TRANSPORTER

