spring:
  application:
    name: payment-service
  datasource:
    url: ${DB_URL_PAYMENT:jdbc:postgresql://localhost:5432/payment_db}
    username: ${DB_USERNAME_PAYMENT:postgres}
    password: ${DB_PASSWORD_PAYMENT:password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8085

momo:
  sandbox:
    base-url: https://sandbox.momodeveloper.mtn.com
    environment: ${MOMO_ENVIRONMENT:sandbox}
    subscription-key: ${MOMO_SUBSCRIPTION_KEY:}
    api-key: ${MOMO_API_KEY:}
